apiVersion: comcast.github.io/v1
kind: KuberhealthyCheck
metadata:
  name: kh-demo-check
  namespace: kuberhealthy
spec:
  runInterval: 5s
  timeout: 30s
  podSpec:
    containers:
      - env:
          - name: GRAFANA_URL
            value: "http://grafana.grafana.svc.cluster.local"
        image: tuxpilgrim/kuberhealthy-custom-check-image:v1
        imagePullPolicy: Always
        name: main
        resources:
          requests:
            cpu: 10m
            memory: 50Mi